### ISSUE TITLE
about the code

### ISSUE THREAD

**Issue by mdjsos** [arthurdouillard/mada.pytorch#1]
Is there a pytorch code that can fully implement MADA?

**Comment by mdjsos** [comment]
Is there a pytorch code that can fully implement MADA?

**Comment by arthurdouillard** [comment]
I don't know, have you google it?

**Comment by mdjsos** [comment]
yes,but nothing about it.I only saw the caffe version on github, but I want the pytorch version.

**Comment by arthurdouillard** [comment]
You could try to build it yourself based on my unfinished implementation. Note that https://github.com/arthurdouillard/mada.pytorch/blob/master/mada.py#L17 I've hardcoded there random input and output features dim, fix those and try to see if the code works.

**Comment by mdjsos** [comment]
Ok,thank you
